'use strict';
// End-to-end checks for the HLS/DASH fixes, against fixtures generated by the
// real ffmpeg and served over HTTP. Parser-level checks always run; anything
// that needs ffmpeg is reported as SKIP when it isn't installed.
const http = require('http');
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { spawnSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const { HlsDownloadTask } = require(path.join(ROOT, 'core', 'hlsDownloadTask'));
const { DashDownloadTask } = require(path.join(ROOT, 'core', 'dashDownloadTask'));
const { parseMediaPlaylist, ivToHex, segmentIv } = require(path.join(ROOT, 'core', 'hls'));
const { parseMpd, selectTracksPerPeriod } = require(path.join(ROOT, 'core', 'dash'));

const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'streams-'));
let fails = 0;
const check = (n, c, d) => {
  console.log(`${c ? 'PASS' : 'FAIL'}  ${n}${d !== undefined ? ' — ' + JSON.stringify(d) : ''}`);
  if (!c) fails++;
};
const skip = (n, why) => console.log(`SKIP ${n} — ${why}`);
const section = (t) => console.log(`\n== ${t} ${'='.repeat(Math.max(0, 60 - t.length))}`);

const hasFfmpeg = spawnSync('ffmpeg', ['-version'], { windowsHide: true }).status === 0;
const hasFfprobe = spawnSync('ffprobe', ['-version'], { windowsHide: true }).status === 0;

function ffmpeg(args, cwd) {
  const r = spawnSync('ffmpeg', ['-v', 'error', '-y', ...args], { cwd, windowsHide: true });
  if (r.status !== 0) throw new Error(`ffmpeg ${args.join(' ')} failed: ${r.stderr}`);
}

function durationOf(file) {
  if (!hasFfprobe) return null;
  const r = spawnSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nk=1:nw=1', file], { windowsHide: true });
  return r.status === 0 ? Number(String(r.stdout).trim()) : null;
}

function serveDir(dir, routes = {}) {
  const hits = [];
  const server = http.createServer((req, res) => {
    const urlPath = decodeURIComponent(req.url.split('?')[0]);
    hits.push({ path: urlPath, range: req.headers.range || null });
    if (routes[urlPath]) return routes[urlPath](req, res);
    const file = path.join(dir, urlPath);
    if (!file.startsWith(dir) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
      res.writeHead(404);
      return res.end();
    }
    const data = fs.readFileSync(file);
    const m = /bytes=(\d+)-(\d*)/.exec(req.headers.range || '');
    if (m) {
      const start = Number(m[1]);
      const end = m[2] ? Number(m[2]) : data.length - 1;
      res.writeHead(206, { 'Content-Length': end - start + 1, 'Content-Range': `bytes ${start}-${end}/${data.length}`, 'Accept-Ranges': 'bytes' });
      return res.end(data.subarray(start, end + 1));
    }
    res.writeHead(200, { 'Content-Length': data.length, 'Accept-Ranges': 'bytes' });
    res.end(data);
  });
  return new Promise((r) => server.listen(0, '127.0.0.1', () => r({ server, port: server.address().port, hits })));
}

function runTask(task, timeoutMs = 60000) {
  return new Promise((resolve) => {
    const t = setTimeout(() => resolve({ result: 'timeout' }), timeoutMs);
    task.on('complete', () => { clearTimeout(t); resolve({ result: 'complete' }); });
    task.on('error', (e) => { clearTimeout(t); resolve({ result: 'error', error: e.message }); });
    task.start().catch((e) => { clearTimeout(t); resolve({ result: 'error', error: e.message }); });
  });
}

const ivFor = (seq) => {
  const b = Buffer.alloc(16);
  b.writeBigUInt64BE(BigInt(seq), 8);
  return b;
};
const aesEncrypt = (key, iv, data) => {
  const c = crypto.createCipheriv('aes-128-cbc', key, iv);
  return Buffer.concat([c.update(data), c.final()]);
};

/**
 * Reads the playlist the downloader handed to ffmpeg and decrypts every stored
 * segment with the IV that playlist declares — exactly what ffmpeg will do.
 * Returns true only if every segment comes back to its original plaintext.
 */
function localPlaylistDecrypts(segDir, key, plaintexts) {
  const text = fs.readFileSync(path.join(segDir, 'local.m3u8'), 'utf8');
  const seqMatch = /#EXT-X-MEDIA-SEQUENCE:(\d+)/.exec(text);
  let seq = seqMatch ? Number(seqMatch[1]) : 0;
  let iv = null;
  let i = 0;
  for (const line of text.split('\n')) {
    if (line.startsWith('#EXT-X-KEY')) {
      const m = /IV=0x([0-9a-f]{32})/i.exec(line);
      iv = m ? Buffer.from(m[1], 'hex') : null; // null -> implicit (sequence number)
    } else if (line && !line.startsWith('#')) {
      const enc = fs.readFileSync(path.join(segDir, line));
      let dec;
      try {
        const d = crypto.createDecipheriv('aes-128-cbc', key, iv || ivFor(seq));
        dec = Buffer.concat([d.update(enc), d.final()]);
      } catch (e) {
        return false;
      }
      if (!dec.equals(plaintexts[i])) return false;
      i++;
      seq++;
    }
  }
  return i === plaintexts.length;
}

(async () => {
  section('HLS parser: IVs, byte ranges, discontinuities');
  {
    const media = parseMediaPlaylist(
      [
        '#EXTM3U',
        '#EXT-X-TARGETDURATION:4',
        '#EXT-X-MEDIA-SEQUENCE:1234',
        '#EXT-X-KEY:METHOD=AES-128,URI="k.bin",IV=0x0123456789ABCDEF0123456789ABCDEF',
        '#EXTINF:4,',
        '#EXT-X-BYTERANGE:1000@0',
        'all.ts',
        '#EXTINF:4,',
        '#EXT-X-BYTERANGE:500',
        'all.ts',
        '#EXT-X-DISCONTINUITY',
        '#EXT-X-KEY:METHOD=AES-128,URI="k.bin"',
        '#EXTINF:4,',
        'c.ts',
        '#EXT-X-ENDLIST',
      ].join('\n'),
      'https://cdn.test/v/index.m3u8'
    );
    const [a, b, c] = media.segments;
    check('explicit IV becomes 0x-hex (not "19088743,...")', a.key.iv === '0x0123456789abcdef0123456789abcdef', a.key.iv);
    check('an implicit IV derives from the media sequence', segmentIv(c) === `0x${(1236).toString(16).padStart(32, '0')}`, segmentIv(c));
    check('byte ranges are carried (offset defaults to the previous end)',
      JSON.stringify([a.range, b.range]) === JSON.stringify([{ start: 0, end: 999 }, { start: 1000, end: 1499 }]), [a.range, b.range]);
    check('the discontinuity is recorded', c.discontinuity === true && !a.discontinuity);
    check('ivToHex rejects garbage', ivToHex('zzz') === null && ivToHex(new Uint32Array([1, 2, 3])) === null);
  }

  section('DASH parser: r="-1" and multiple periods');
  {
    const tpl = (sList) => `<?xml version="1.0"?>
<MPD mediaPresentationDuration="PT8S" type="static"><Period>
 <AdaptationSet contentType="video"><SegmentTemplate timescale="1000" media="v-$Time$.m4s" initialization="v.mp4">
  <SegmentTimeline>${sList}</SegmentTimeline></SegmentTemplate>
  <Representation id="v" bandwidth="1" width="10" height="10"/></AdaptationSet></Period></MPD>`;
    const untilEnd = parseMpd(tpl('<S t="0" d="2000" r="-1"/>'), 'https://x.test/m.mpd');
    check('r="-1" repeats to the end of the period (8s / 2s = 4)', untilEnd.video[0].segments.length === 4, untilEnd.video[0].segments.length);
    const untilNext = parseMpd(tpl('<S t="0" d="1000" r="-1"/><S t="4000" d="2000" r="1"/>'), 'https://x.test/m.mpd');
    const times = untilNext.video[0].segments.map((s) => Number(/v-(\d+)/.exec(s.url)[1]));
    check('r="-1" repeats up to the next S@t', JSON.stringify(times) === JSON.stringify([0, 1000, 2000, 3000, 4000, 6000]), times);

    const multi = parseMpd(`<?xml version="1.0"?>
<MPD mediaPresentationDuration="PT10S" type="static">
 <Period id="a" duration="PT4S"><AdaptationSet contentType="video"><SegmentTemplate timescale="1" duration="2" media="a$Number$.m4s" initialization="ai.mp4"/>
  <Representation id="a720" bandwidth="2000" width="1280" height="720"/><Representation id="a360" bandwidth="500" width="640" height="360"/></AdaptationSet></Period>
 <Period id="b"><AdaptationSet contentType="video"><SegmentTemplate timescale="1" duration="2" media="b$Number$.m4s" initialization="bi.mp4"/>
  <Representation id="b720" bandwidth="1900" width="1280" height="720"/><Representation id="b360" bandwidth="450" width="640" height="360"/></AdaptationSet></Period>
</MPD>`, 'https://x.test/m.mpd');
    check('both periods are parsed', multi.periods.length === 2, multi.periods.length);
    check('the second period gets the remaining 6s', multi.periods[1].durationSec === 6 && multi.periods[1].video[0].segments.length === 3, multi.periods[1].durationSec);
    const picks = selectTracksPerPeriod(multi, 1).map((s) => s.video.id);
    check('the chosen quality carries across periods', JSON.stringify(picks) === JSON.stringify(['a360', 'b360']), picks);
  }

  if (!hasFfmpeg) {
    skip('HLS/DASH end-to-end runs', 'ffmpeg is not installed');
  } else {
    // --- fixtures -------------------------------------------------------------
    const fx = path.join(TMP, 'fx');
    fs.mkdirSync(fx, { recursive: true });
    ffmpeg(['-f', 'lavfi', '-i', 'testsrc=duration=4:size=160x120:rate=10', '-c:v', 'mpeg4', '-g', '10', '-f', 'mpegts', 'src.ts'], fx);
    ffmpeg(['-i', 'src.ts', '-c', 'copy', '-f', 'hls', '-hls_time', '1', '-hls_list_size', '0', '-hls_segment_filename', 'plain%03d.ts', 'plain.m3u8'], fx);
    const plainNames = fs.readFileSync(path.join(fx, 'plain.m3u8'), 'utf8').split('\n').filter((l) => l && !l.startsWith('#'));
    const plaintexts = plainNames.map((n) => fs.readFileSync(path.join(fx, n)));
    const key = crypto.randomBytes(16);
    fs.writeFileSync(path.join(fx, 'key.bin'), key);

    // Implicit IV: each segment encrypted with its own media sequence number.
    const SEQ = 1234;
    const implicitLines = ['#EXTM3U', '#EXT-X-TARGETDURATION:2', `#EXT-X-MEDIA-SEQUENCE:${SEQ}`, '#EXT-X-KEY:METHOD=AES-128,URI="key.bin"'];
    plaintexts.forEach((pt, i) => {
      fs.writeFileSync(path.join(fx, `imp${i}.ts`), aesEncrypt(key, ivFor(SEQ + i), pt));
      implicitLines.push('#EXTINF:1.0,', `imp${i}.ts`);
    });
    implicitLines.push('#EXT-X-ENDLIST');
    fs.writeFileSync(path.join(fx, 'implicit.m3u8'), implicitLines.join('\n'));

    // Explicit IV: one IV for every segment, declared in the tag.
    const EXPLICIT = Buffer.from('00112233445566778899aabbccddeeff', 'hex');
    const explicitLines = ['#EXTM3U', '#EXT-X-TARGETDURATION:2', '#EXT-X-MEDIA-SEQUENCE:7', `#EXT-X-KEY:METHOD=AES-128,URI="key.bin",IV=0x${EXPLICIT.toString('hex')}`];
    plaintexts.forEach((pt, i) => {
      fs.writeFileSync(path.join(fx, `exp${i}.ts`), aesEncrypt(key, EXPLICIT, pt));
      explicitLines.push('#EXTINF:1.0,', `exp${i}.ts`);
    });
    explicitLines.push('#EXT-X-ENDLIST');
    fs.writeFileSync(path.join(fx, 'explicit.m3u8'), explicitLines.join('\n'));

    // Single-file HLS: every segment is a byte range of one .ts.
    ffmpeg(['-i', 'src.ts', '-c', 'copy', '-f', 'hls', '-hls_time', '1', '-hls_list_size', '0', '-hls_flags', 'single_file', '-hls_segment_filename', 'single.ts', 'single.m3u8'], fx);

    // A master playlist that is only reachable through a redirect, with
    // relative URIs that only resolve against the redirect TARGET.
    fs.mkdirSync(path.join(fx, 'real'), { recursive: true });
    fs.writeFileSync(path.join(fx, 'real', 'master.m3u8'), '#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=100000\nmedia.m3u8\n');
    const redirectMedia = ['#EXTM3U', '#EXT-X-TARGETDURATION:2', '#EXT-X-MEDIA-SEQUENCE:0'];
    plainNames.forEach((n) => {
      fs.copyFileSync(path.join(fx, n), path.join(fx, 'real', n));
      redirectMedia.push('#EXTINF:1.0,', n);
    });
    redirectMedia.push('#EXT-X-ENDLIST');
    fs.writeFileSync(path.join(fx, 'real', 'media.m3u8'), redirectMedia.join('\n'));

    const { server, port, hits } = await serveDir(fx, {
      '/redir/master.m3u8': (req, res) => {
        res.writeHead(302, { Location: '/real/master.m3u8' });
        res.end();
      },
    });
    const base = `http://127.0.0.1:${port}`;
    const srcDuration = durationOf(path.join(fx, 'src.ts'));

    section('HLS AES-128 with an implicit IV (media sequence 1234)');
    {
      const dest = path.join(TMP, 'out', 'implicit.mp4');
      const task = new HlsDownloadTask({ playlistUrl: `${base}/implicit.m3u8`, destPath: dest, keepSegments: true });
      const r = await runTask(task);
      check('downloaded and remuxed', r.result === 'complete' && fs.existsSync(dest), r);
      check('every segment decrypts to its plaintext with the IV the local playlist declares',
        localPlaylistDecrypts(task.segDir, key, plaintexts));
      const d = durationOf(dest);
      if (d != null && srcDuration != null) check('output runs as long as the source', Math.abs(d - srcDuration) < 0.6, { d, srcDuration });
    }

    section('HLS AES-128 with an explicit IV');
    {
      const dest = path.join(TMP, 'out', 'explicit.mp4');
      const task = new HlsDownloadTask({ playlistUrl: `${base}/explicit.m3u8`, destPath: dest, keepSegments: true });
      const r = await runTask(task);
      check('downloaded and remuxed', r.result === 'complete' && fs.existsSync(dest), r);
      check('every segment decrypts to its plaintext with the IV the local playlist declares',
        localPlaylistDecrypts(task.segDir, key, plaintexts));
    }

    section('HLS single-file (#EXT-X-BYTERANGE) stream');
    {
      const dest = path.join(TMP, 'out', 'single.mp4');
      const before = hits.length;
      const task = new HlsDownloadTask({ playlistUrl: `${base}/single.m3u8`, destPath: dest, keepSegments: true });
      const r = await runTask(task);
      check('downloaded and remuxed', r.result === 'complete' && fs.existsSync(dest), r);
      const ranged = hits.slice(before).filter((h) => h.path === '/single.ts');
      check('each segment was fetched as a byte range', ranged.length > 1 && ranged.every((h) => h.range), ranged.length);
      const stored = fs.readdirSync(task.segDir).filter((f) => /^seg_\d+\.ts$/.test(f));
      const total = stored.reduce((a, f) => a + fs.statSync(path.join(task.segDir, f)).size, 0);
      check('the slices add up to the file exactly once (no N whole copies)', total === fs.statSync(path.join(fx, 'single.ts')).size, { total });
      const d = durationOf(dest);
      if (d != null && srcDuration != null) check('output runs as long as the source', Math.abs(d - srcDuration) < 0.6, { d, srcDuration });
    }

    section('HLS master reached through a redirect');
    {
      const dest = path.join(TMP, 'out', 'redirected.mp4');
      const task = new HlsDownloadTask({ playlistUrl: `${base}/redir/master.m3u8`, destPath: dest });
      const r = await runTask(task);
      check('relative URIs resolved against the redirect target', r.result === 'complete' && fs.existsSync(dest), r);
    }
    server.close();

    // --- DASH: two periods, one using r="-1" ----------------------------------
    section('DASH with two periods');
    {
      const dfx = path.join(TMP, 'dash');
      const make = (name, pattern, seconds) => {
        fs.mkdirSync(path.join(dfx, name), { recursive: true });
        ffmpeg(['-f', 'lavfi', '-i', `${pattern}=duration=${seconds}:size=160x120:rate=10`, '-c:v', 'mpeg4', '-g', '10', `${name}.mp4`], dfx);
        ffmpeg(['-i', `${name}.mp4`, '-c', 'copy', '-f', 'dash', '-seg_duration', '1', '-use_template', '1', '-use_timeline', '1',
          '-init_seg_name', 'init-$RepresentationID$.m4s', '-media_seg_name', 'chunk-$RepresentationID$-$Number%05d$.m4s',
          // Forward slash on purpose: ffmpeg's dash muxer only splits the
          // manifest path on '/', and with a backslash it writes the segments
          // into the working directory instead of beside the manifest.
          `${name}/manifest.mpd`], dfx);
        const mpd = fs.readFileSync(path.join(dfx, name, 'manifest.mpd'), 'utf8');
        return /<AdaptationSet[\s\S]*<\/AdaptationSet>/.exec(mpd)[0];
      };
      const setA = make('a', 'testsrc', 2).replace(/ r="1"/, ' r="-1"');
      const setB = make('b', 'testsrc2', 3);
      const combined = `<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" type="static" mediaPresentationDuration="PT5.0S">
 <Period id="p0" start="PT0S" duration="PT2.0S"><BaseURL>a/</BaseURL>${setA}</Period>
 <Period id="p1" start="PT2.0S" duration="PT3.0S"><BaseURL>b/</BaseURL>${setB}</Period>
</MPD>`;
      fs.writeFileSync(path.join(dfx, 'two.mpd'), combined);
      const srv = await serveDir(dfx);
      const dest = path.join(TMP, 'out', 'two-periods.mp4');
      const task = new DashDownloadTask({ mpdUrl: `http://127.0.0.1:${srv.port}/two.mpd`, destPath: dest });
      let variant = null;
      task.on('variant-selected', (v) => (variant = v));
      const r = await runTask(task);
      check('downloaded, muxed and concatenated', r.result === 'complete' && fs.existsSync(dest), r);
      check('both periods were planned', variant && variant.periods === 2, variant);
      const d = durationOf(dest);
      if (d != null) check('output covers both periods (~5s, not the first 2s)', d > 4.4 && d < 5.6, { d });
      srv.server.close();
    }
  }

  try { fs.rmSync(TMP, { recursive: true, force: true }); } catch {}
  console.log(`\n${fails === 0 ? 'ALL STREAM HARDENING TESTS PASSED' : fails + ' TEST(S) FAILED'}`);
  process.exit(fails === 0 ? 0 : 1);
})().catch((e) => {
  console.error('ERROR', e);
  process.exit(1);
});
