'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  list: () => ipcRenderer.invoke('queue:list'),
  add: (payload) => ipcRenderer.invoke('queue:add', payload),
  pause: (id) => ipcRenderer.invoke('queue:pause', id),
  resume: (id) => ipcRenderer.invoke('queue:resume', id),
  cancel: (id) => ipcRenderer.invoke('queue:cancel', id),
  remove: (id) => ipcRenderer.invoke('queue:remove', id),
  pauseAll: () => ipcRenderer.invoke('queue:pauseAll'),
  resumeAll: () => ipcRenderer.invoke('queue:resumeAll'),
  startAll: () => ipcRenderer.invoke('queue:startAll'),
  refreshUrl: (id, url) => ipcRenderer.invoke('queue:refreshUrl', { id, url }),
  hold: (id) => ipcRenderer.invoke('queue:hold', id),
  startQueue: (queueId) => ipcRenderer.invoke('queue:startQueue', queueId),
  stopQueue: (queueId) => ipcRenderer.invoke('queue:stopQueue', queueId),
  reorder: (id, delta) => ipcRenderer.invoke('queue:reorder', { id, delta }),
  listQueues: () => ipcRenderer.invoke('queues:list'),
  createQueue: (name, maxConcurrent) => ipcRenderer.invoke('queues:create', { name, maxConcurrent }),
  renameQueue: (queueId, name) => ipcRenderer.invoke('queues:rename', { queueId, name }),
  setQueueConcurrency: (queueId, maxConcurrent) => ipcRenderer.invoke('queues:setConcurrency', { queueId, maxConcurrent }),
  deleteQueue: (queueId) => ipcRenderer.invoke('queues:delete', queueId),
  moveToQueue: (ids, queueId) => ipcRenderer.invoke('queues:move', { ids, queueId }),
  onQueuesChanged: (cb) => ipcRenderer.on('queues:changed', (_e, queues) => cb(queues)),
  isQueueRunning: () => ipcRenderer.invoke('queue:isQueueRunning'),
  onQueueStateChanged: (cb) => ipcRenderer.on('queue:state-changed', (_e, state) => cb(state)),
  openFile: (destPath) => ipcRenderer.invoke('shell:openFile', destPath),
  showInFolder: (destPath) => ipcRenderer.invoke('shell:showInFolder', destPath),
  deleteFile: (destPath) => ipcRenderer.invoke('shell:deleteFile', destPath),
  getClientCount: () => ipcRenderer.invoke('bridge:clientCount'),
  pickDestDir: () => ipcRenderer.invoke('dialog:pickDestDir'),
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (cfg) => ipcRenderer.invoke('config:set', cfg),
  onItemAdded: (cb) => ipcRenderer.on('queue:item-added', (_e, item) => cb(item)),
  onItemUpdated: (cb) => ipcRenderer.on('queue:item-updated', (_e, item) => cb(item)),
  onItemRemoved: (cb) => ipcRenderer.on('queue:item-removed', (_e, info) => cb(info)),
  onDuplicateDetected: (cb) => ipcRenderer.on('queue:duplicate', (_e, info) => cb(info)),
  startGrabber: (opts) => ipcRenderer.invoke('grabber:start', opts),
  cancelGrabber: () => ipcRenderer.invoke('grabber:cancel'),
  onGrabberPageStart: (cb) => ipcRenderer.on('grabber:page-start', (_e, p) => cb(p)),
  onGrabberAssetFound: (cb) => ipcRenderer.on('grabber:asset-found', (_e, a) => cb(a)),
  onGrabberPageError: (cb) => ipcRenderer.on('grabber:page-error', (_e, err) => cb(err)),
  onGrabberDone: (cb) => ipcRenderer.on('grabber:done', (_e, result) => cb(result)),
});
